kuaishou_danmu_cookie = "kwfv1=PnGU+9+Y8008S+nH0U+0mjPf8fP08f+98f+nLlwnrIP9P9G98YPf8jPBQSweS0+nr9G0mD8B+fP/L98/qlPe4f8B808nPlwBQD8/L9Gfz0+AqMweqlGnPEPe+SPAGFP08Y+epYPe8YPArFGArh+fpSG0rUwnchwe4jw/mYwncIP9L=; did=web_35e790c11bc3488abb3c447b325fb678; clientid=3; kpn=KUAISHOU_VISION; kuaishou.live.bfb1s=3e261140b0cf7444a0ba411c6f227d88; kpf=PC_WEB; kwpsecproductname=PCLive; kwssectoken=1YktqGgY2Gm/2SZ2NptGGAn5KyzKS7Us3PWWvAKJg40nFf3zv0RZjOhCrGr3cqJMOkllYFYC8EzQYb9KDjpdRw==; kwscode=8aad2d2b324d894df87afb11e3e354954b83d602bf936b28b41ffd3a68336160; client_key=65890b29; kuaishou.server.webday7_ph=d4d78bd3ae03a059c58d46d7b1d72fca4689; kuaishou.server.webday7_st=ChprdWFpc2hvdS5zZXJ2ZXIud2ViZGF5Ny5zdBKwAbresMjLjKWmGpxo2474_JxPxtK3xU9TlfPRj1dnYqn8XT8F08hYUcchGvScijL0TBJTB2FsV2oihzI3PIfytgLaOx-DKo7p2r-EKd6Z1a-U-dyZ8LwWFFEE1CqEuAUjzmCK8h-aCK_H8wfwUHixh75WFQPFZgcL_wVJHx2I5noqe-CE1L3yQaQHadW_zVlZI_U-GTmhxnSUzMqjKSMF0BUMylnxwSk5DQRG1P_2q0G2GhI5Nsn9KZ0YHUglnTL0rRQUJE4iIHvgCFRithHXGBod7on-0Gb1sP0DX31d8WuzodsOYuPlKAUwAQ\""

[[guest_accounts]]
platform = "douyin"
cookies = ""
extra = ""

[[guest_accounts]]
platform = "kuaishou"
cookies = ""
extra = ""

[[guest_accounts]]
platform = "tiktok"
cookies = ""
extra = ""

[[guest_accounts]]
platform = "bilibili"
cookies = ""
extra = ""

[[guest_accounts]]
platform = "huya"
cookies = ""
extra = ""

[[login_accounts]]
platform = "douyin"
cookies = ""
extra = ""
