

[[guest_accounts]]
platform = "douyin"
cookies = ""
extra = ""

[[guest_accounts]]
platform = "kuaishou"
cookies = ""
extra = ""

[[guest_accounts]]
platform = "tiktok"
cookies = ""
extra = ""

[[guest_accounts]]
platform = "bilibili"
cookies = ""
extra = ""

[[guest_accounts]]
platform = "huya"
cookies = ""
extra = ""

[[login_accounts]]
platform = "douyin"
cookies = ""
extra = ""

[[login_accounts]]
platform = "kuaishou"
cookies = ""
extra = ""

[[login_accounts]]
platform = "tiktok"
cookies = ""
extra = ""

[[login_accounts]]
platform = "bilibili"
cookies = ""
extra = ""

[[login_accounts]]
platform = "huya"
cookies = ""
extra = ""
