cache = "./cache"
output = "./output"
live_start_notify = true
live_end_notify = true
clip_notify = true
post_notify = true
auto_subtitle = false
subtitle_generator_type = "whisper_online"
whisper_model = "./whisper_model.bin"
whisper_prompt = "这是一段中文 你们好"
openai_api_key = ""
clip_name_format = "[{room_id}][{live_id}][{title}][{created_at}].mp4"

[douyin_passport]
provider_url = ""
sign = ""
qs = ""
passport_jssdk_version = "3.1.3"
passport_jssdk_type = "normal"
is_from_ttaccountsdk = "1"
aid = "6383"
language = "zh"
account_app_language = "zh-CN"
next = "https://live.douyin.com"
need_short_url = "true"
need_logo = "false"
is_new_login = "1"
is_from_iesaccountsaas = "1"
account_sdk_source = "web"
account_sdk_source_info = ""
p_ui = "2.1.4"
p_ca = "4.0.17"
p_ca_real = "1.0.0.729"
p_js_v = "3.1.3"
p_js_t = "pro"
p_zt = "3.3.10"
p_ver = "1.1.3"
p_ver_real = "0"
request_host = "https://live.douyin.com"
p_bd = "1.0.1.19-fix.01"
p_ts = ""
p_no = ""
biz_trace_id = ""
device_platform = "web_app"
ms_token = ""
a_bogus = ""
x_tt_passport_csrf_token = ""
x_tt_passport_aid_sign = ""
x_tt_passport_trace_id = ""
x_tt_passport_verify_portrait = ""
x_tt_session_dtrait = ""
qr_origin = "https://live.douyin.com"
qr_referer = "https://live.douyin.com/"

[auto_generate]
enabled = false
encode_danmu = false
