cache = "./cache"
output = "./output"
live_start_notify = true
live_end_notify = true
clip_notify = true
post_notify = true
auto_subtitle = false
subtitle_generator_type = "whisper"
whisper_model = "whisper_model.bin"
whisper_prompt = "这是一段中文 你们好"
openai_api_endpoint = "https://api.openai.com/v1"
openai_api_key = ""
clip_name_format = "[{room_id}][{live_id}][{title}][{created_at}].mp4"
status_check_interval = 5
whisper_language = "auto"
webhook_url = ""
powerlive_key = ""
http_proxy = ""
https_proxy = ""

[[default_accounts]]
platform = "tiktok"
cookies = "_ttp=2mqwLlPdteaYKZu7vLUHm4kbjgD; tiktok_webapp_theme=dark; delay_guest_mode_vid=5; passport_csrf_token=2c3a099f93f1c872e72e6c13c066aa81; passport_csrf_token_default=2c3a099f93f1c872e72e6c13c066aa81; d_ticket=c71b86f739bd09f3292521e65a60848791f65; store-idc=alisg; store-country-code-src=uid; tt-target-idc=alisg; g_state={"i_l":0,"i_ll":1769287956819}; multi_sids=7314926308239590401%3A4cba802e3edb0761f5b7054b9fe03336%7C7237411787456201734%3A68b3f69029e0cb03a912fe5748fe07a9; cmpl_token=AgQYAPO0_hfkTtK0Tp0LVL-dP_MUh-V3lL-DIWCibPA; passport_auth_status=e8996252b460ecb92cbac424b1948d25%2C52702c3ca5e2d14c78362bd2c3c01d8a; passport_auth_status_ss=e8996252b460ecb92cbac424b1948d25%2C52702c3ca5e2d14c78362bd2c3c01d8a; sid_guard=68b3f69029e0cb03a912fe5748fe07a9%7C1769287973%7C15552000%7CThu%2C+23-Jul-2026+20%3A52%3A53+GMT; uid_tt=53ca95bf70e88e270c18c4ff79e1b0b3c8f8ca0c041cf3f495c74494a7f8c7de; uid_tt_ss=53ca95bf70e88e270c18c4ff79e1b0b3c8f8ca0c041cf3f495c74494a7f8c7de; sid_tt=68b3f69029e0cb03a912fe5748fe07a9; sessionid=68b3f69029e0cb03a912fe5748fe07a9; sessionid_ss=68b3f69029e0cb03a912fe5748fe07a9; tt_session_tlb_tag=sttt%7C5%7CaLP2kCngywOpEv5XSP4Hqf_________A7tIjhHwqm-zWW70Orl3CqpZVaBre2Pv-op4ivK_MwA8%3D; sid_ucp_v1=1.0.1-KGI5MGUyZDQzN2Y3OGZkNDNiYzA1MTE5Y2I3ZGQ2MjI1OTI2NTc0NzYKIQiGiLXkzfWcuGQQpeLUywYYswsgDDDN58GjBjgIQBJIBBADGgJteSIgNjhiM2Y2OTAyOWUwY2IwM2E5MTJmZTU3NDhmZTA3YTkyTgogTZNWRVSV4-iSdYW3jtX3SX4WebUFnfWeqKFavFkGDVoSIJL3xRDa9YVKkQHk8GTd_UVn9dop6HwtNwOIkXcNfe8iGAMiBnRpa3Rvaw; ssid_ucp_v1=1.0.1-KGI5MGUyZDQzN2Y3OGZkNDNiYzA1MTE5Y2I3ZGQ2MjI1OTI2NTc0NzYKIQiGiLXkzfWcuGQQpeLUywYYswsgDDDN58GjBjgIQBJIBBADGgJteSIgNjhiM2Y2OTAyOWUwY2IwM2E5MTJmZTU3NDhmZTA3YTkyTgogTZNWRVSV4-iSdYW3jtX3SX4WebUFnfWeqKFavFkGDVoSIJL3xRDa9YVKkQHk8GTd_UVn9dop6HwtNwOIkXcNfe8iGAMiBnRpa3Rvaw; store-country-code=my; tt-target-idc-sign=n5XuJXX-uRrRCxymRLolVDnPVQuqR5A2CDC_R82cwhZ4uMyX4LHPnmi_Zo3r3xMyY33Nw4zI7tusVsOvl8y3F_7OtfY9sqxb1TxIceqkxbG7nGw2VcrkXyPrg25mDMyPNlvhw_QRc-cYqQQXlDLUXBXFrMAhVEnkvnsgegVZq_QnaLQNtskndIHeJiIEVV1F0_XdzPaSgpfdOgoCyfbTgubPNYsYZ55B2cy6EJI-Fyq2uLl6RzX-ca_mfMgize_V3oGPsOsZ6xOdro64LaHiY-N_Bayd1OFtznJllJLYelGdTAgpIHOv5tpX-wMEvOKoIaDyEnUbllHZc50d87pWv5IuNz-2IP-RCOovUk48cuZndXgPT8131ovRgS1ho_fr_7i5WNhR-5e6MN7OlWImXb6ZV6PxuwBATddWuLWxu117Wnxn2fmOxdkqjlKQOPDU9mqjCq8fAtpiEbGp2Nl6gMAYeUA92enop_2hYexvr-EL_Ia03P2SgbTqragRzugS; last_login_method=google_oneclick; tt_csrf_token=himEVJcz-WISyHV0ktkwjAhMNmXTU0wehQmk; __user_7237411787456201734=1769339546683; csrfToken=IOOSlta7-AxA2Ut-aMU3LdcXc86GZHMATp1Q; tiktok_webapp_theme_source=dark; store-country-sign=MEIEDKM5c963AC6CY4zSJwQgnEVz2V7GPsh4HyAB30yfk0WQEcGB8MRR_Fw1rmjqWWIEEKR5DxeA6emKN3JZhZjmWLM; odin_tt=0085ab8e3a399e0ab6d605b27aeb40f8198bfdba6f22cd43892740c8d905b13250dfec58204690f23d7ad7c274f5539c2343bb91651c4778df02b3c8b0212dc34ef1ecdc0b541671c7e76dabcacf4221; ttwid=1%7Cs-WBMldYRoKNSZTin9sJ3eZiD3KqqUQANU7JQKqKCQw%7C1769356062%7Cbf42237ee2a610a1be54edd2a1731965ba0366a95da828885f8d073bc3866912; msToken=nO9cDDpEgHNdlVrH2Uns9qcSvuOpBb75vYKN04s9Uuaqyg2nkUSHvi-VGL0NTWtXYd1HUSVjGPPCC2KXaP4_InUypsxb5vogUdOWI6pGq2obxH0vHh1Cs52vE_BcQAQhUYtkzlnoFsFW-9M=; msToken=lrmtEj2Wh4sN_nD_K1j4wzMK-O1vKeop19Nt6STwwHm-N_CCNF9Wx8ecmbZKOxXwVJeSmr2WYUbmG-vX6l3tRkxNz39LXF-izj1noAG0_lElPHya6_9-vzQ7ZrMfk_GstRHh8aFLOT0X5Lc=; tt_chain_token=REgh9X2jeFqwuHhQMcbw+Q=="

use_default_accounts = false

[auto_generate]
enabled = false
encode_danmu = false

[danmu_ass_options]
font_size = 36.0
opacity = 0.8

[douyin_passport]
provider_url = ""
sign = ""
qs = ""
passport_jssdk_version = "3.1.3"
passport_jssdk_type = "normal"
is_from_ttaccountsdk = "1"
aid = "6383"
language = "zh"
account_app_language = "zh-CN"
next = "https://live.douyin.com"
need_short_url = "true"
need_logo = "false"
is_new_login = "1"
is_from_iesaccountsaas = "1"
account_sdk_source = "web"
account_sdk_source_info = ""
service = "https://live.douyin.com"
p_ui = "2.1.4"
p_ca = "4.0.17"
p_ca_real = "1.0.0.729"
p_js_v = "3.1.3"
p_js_t = "pro"
p_zt = "3.3.10"
p_ver = "1.1.3"
p_ver_real = "0"
request_host = "https://live.douyin.com"
p_bd = "1.0.1.19-fix.01"
p_ts = ""
p_no = ""
biz_trace_id = ""
device_platform = "web_app"
verify_fp = ""
fp = ""
ms_token = ""
a_bogus = ""
x_tt_passport_csrf_token = ""
x_tt_passport_aid_sign = ""
x_tt_passport_trace_id = ""
x_tt_passport_verify_portrait = ""
x_tt_session_dtrait = ""
qr_origin = "https://live.douyin.com"
qr_referer = "https://live.douyin.com/"

